Repository woowa-techcamp-2021/deal-8, pull requests merged in 2021-07, with the labels that each got.

#2 Github Template 추가와 팀원 자기소개 내용입니다.
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  README.md
Labels: documentation

#34 [Setting] Backend 와 Frontend 개발 환경 세팅입니다.
  backend/.gitignore
  backend/app.mjs
  backend/bin/www.mjs
  backend/package-lock.json
  backend/package.json
  backend/public/stylesheets/style.css
  backend/routes/index.mjs
  backend/views/error.ejs
  backend/views/index.ejs
  frontend/.babel.config.json
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/public/css/login.css
  frontend/public/css/main.css
  frontend/public/login.html
  frontend/public/main.html
  frontend/src/app.html
  frontend/src/app.js
  frontend/src/mainService.js
  frontend/webpack.config.js
Labels: BE

#41 [Setting] Webpack Dev 서버 설정과 프론트엔드 프레임워크 초안 코드입니다.
  .github/pull_request_template.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app.html
  frontend/src/app.js
  frontend/src/mainService.js
  frontend/src/views/AbstractView.js
  frontend/src/views/HomeView.js
  frontend/src/views/LoginView.js
  frontend/src/views/ProductView.js
  frontend/webpack.config.js
Labels: enhancement

#43 [Markdown] Category 화면관련 레이아웃 및 스타일 작업 내용입니다. #6
  frontend/public/category.html
  frontend/public/css/category.css
  frontend/public/css/common/basic_header.css
  frontend/public/css/common/global_color.css
  frontend/public/css/login.css
  frontend/public/css/profile.css
  frontend/public/css/signup.css
  frontend/public/login.html
  frontend/public/profile.html
  frontend/public/signup.html
Labels: FE

#44 [MarkUp] 메인페이지 퍼블리싱
  .vscode/extensions.json
  frontend/.gitignore
  frontend/public/css/main.css
  frontend/public/css/normalize.css
  frontend/public/icon/category-white.svg
  frontend/public/icon/category.svg
  frontend/public/icon/chat.svg
  frontend/public/icon/gps-white.svg
  frontend/public/icon/gps.svg
  frontend/public/icon/interest-small.svg
  frontend/public/icon/interest.svg
  frontend/public/icon/menu-white.svg
  frontend/public/icon/menu.svg
  frontend/public/icon/plus.svg
  frontend/public/icon/profile-white.svg
  frontend/public/icon/profile.svg
  frontend/public/image/example-cooler.svg
  frontend/public/main.html
Labels: FE

#45 [Markup] 글쓰기 레이아웃과 스타일링
  frontend/.gitignore
  frontend/public/category.html
  frontend/public/createPost.html
  frontend/public/css/common/basic_header.css
  frontend/public/css/createPost.css
  frontend/public/icon/check.svg
  frontend/public/icon/chevron-left.svg
  frontend/public/icon/close-white.svg
  frontend/public/icon/close.svg
  frontend/public/icon/image.svg
  frontend/public/icon/map-pin.svg
Labels: FE

#48 [Markup] 상품 상세 페이지 레이아웃과 스타일링 #9
  frontend/public/createPost.html
  frontend/public/css/detailPost.css
  frontend/public/detailPost.html
  frontend/public/icon/chevron-down.svg
  frontend/public/icon/more-vertical.svg
  frontend/public/image/example-skate.svg
Labels: FE

#51 [Markup] 채팅 상세 페이지 레이아웃과 스타일 #11
  frontend/public/chat.html
  frontend/public/css/chat.css
  frontend/public/icon/log-out.svg
  frontend/public/icon/send.svg
  frontend/public/js/chat.js
Labels: FE

#57 fix: 퍼블리싱 리뷰를 하다가 발견한 버그 수정
  frontend/public/detailPost.html
  frontend/public/js/menu/menuEvent.js
Labels: bug

#68 [Refactoring] 잡다한 리펙토링입니다. 내용 참고 해주세요.
  frontend/src/api/chat.js
  frontend/src/api/product.js
  frontend/src/common/views/ProductListView.js
  frontend/src/page/HomePage/index.js
  frontend/src/page/LoginPage/index.js
  frontend/src/page/MenuPage/index.js
  frontend/src/page/MenuPage/views/ChatRoomListView.js
  frontend/src/page/ProductDetailPage/Controller.js
  frontend/src/page/ProductDetailPage/Store.js
  frontend/src/page/ProductDetailPage/index.js
  frontend/src/page/ProfilePage/index.js
  frontend/src/page/SignupPage/index.js
Labels: FE

#76 [FE] 내 동네 설정하기 화면 기능 구현 #21
  frontend/src/api/user.js
  frontend/src/page/LocationPage/Controller.js
  frontend/src/page/LocationPage/Store.js
  frontend/src/page/LocationPage/index.js
  frontend/src/page/LocationPage/views/AddLocationModalView.js
  frontend/src/page/LocationPage/views/DeleteLocationModalView.js
  frontend/src/page/LocationPage/views/LocationCommentView.js
  frontend/src/page/LocationPage/views/LocationListView.js
  frontend/src/page/ProductDetailPage/views/ProductDetailHeaderView.js
  frontend/src/page/ProductDetailPage/views/ProductDetailView.js
  frontend/src/public/css/detailPost.css
  frontend/src/public/css/location.css
  frontend/src/public/css/main.css
  frontend/src/public/svg/add.svg
Labels: FE

#101 [FE/BE] 이미지 업로드와 글쓰기 기능 구현 완료
  backend/process.json
  backend/src/clearDatabaseTables.js
  backend/src/createDatabaseTables.js
  backend/src/model/Product/AbstractProductStore.js
  backend/src/model/Product/Store/MySQLProductStore.js
  backend/src/populateExampleData.js
  backend/src/routes/api/account/index.js
  backend/src/routes/api/auth/index.js
  backend/src/routes/api/product/index.js
  backend/src/routes/index.js
  backend/src/views/file.ejs
  frontend/src/api/product.js
  frontend/src/common/views/ProductListView.js
  frontend/src/page/CreatePostPage/Controller.js
  frontend/src/page/ProductDetailPage/views/ProductImageListView.js
  frontend/src/public/css/detailPost.css
  frontend/webpack.config.js
Labels: BE, FE

#104 [Refactor] Category API 디렉토리이동 과 Frontend Category 번호가아니라 이름으로 표시
  backend/src/model/Category/AbstractCategoryStore.js
  backend/src/model/Category/Store/MySQLCategoryStore.js
  backend/src/model/Product/Store/MySQLProductStore.js
  backend/src/routes/api/category/index.js
  backend/src/routes/api/index.js
  backend/src/routes/api/product/index.js
  frontend/src/api/product.js
  frontend/src/page/CreatePostPage/Controller.js
  frontend/src/page/CreatePostPage/Store.js
  frontend/src/page/CreatePostPage/views/CategorySelectView.js
  frontend/src/page/HomePage/Controller.js
  frontend/src/page/LocationPage/views/AddLocationModalView.js
  frontend/src/page/LoginPage/Controller.js
  frontend/src/page/ProductDetailPage/Controller.js
  frontend/src/page/ProductDetailPage/Store.js
  frontend/src/page/ProductDetailPage/views/ProductDetailView.js
Labels: bug

#115 Add: 채팅상세화면에서 각 상화에 맞는 Back 화면 네비게이션 개선
  frontend/src/page/ChatRoomListPage/Controller.js
  frontend/src/page/ChatRoomListPage/Store.js
  frontend/src/page/ChatRoomListPage/views/ChatRoomListContentView.js
  frontend/src/page/ChatRoomListPage/views/chatRoomListHeaderView.js
  frontend/src/page/ChatRoomPage/Controller.js
  frontend/src/page/MenuPage/Controller.js
  frontend/src/page/ProductDetailPage/Controller.js
  frontend/src/page/ProductDetailPage/views/ProductDetailFooterView.js
  frontend/src/router.js
Labels: bug

#122 [Bugfix & Deploay] 배포환경을 위한 세팅과 버그 수정내용입니다.
  backend/.gitignore
  backend/package-lock.json
  backend/src/clearDatabaseTables.js
  backend/src/createDatabaseTables.js
  backend/src/model/Product/Store/MySQLProductStore.js
  backend/src/populateExampleData.js
  backend/src/routes/index.js
  deploy.sh
  frontend/HEAD
  frontend/package-lock.json
  frontend/package.json
  frontend/src/page/ChatRoomListPage/Controller.js
  frontend/src/page/ChatRoomListPage/index.js
  frontend/src/page/ChatRoomListPage/views/ChatRoomListHeaderView.js
  frontend/src/page/HomePage/Controller.js
  frontend/src/page/ProductDetailPage/Controller.js
  frontend/webpack.common.js
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: bug

#125 메뉴 탭화면에서 자기가 판매중인 상품을 제거할 수 있는 모달 구현
  backend/src/model/Product/Store/MySQLProductStore.js
  backend/src/routes/api/account/index.js
  frontend/src/common/views/ModalView.js
  frontend/src/page/LocationPage/Controller.js
  frontend/src/page/LocationPage/index.js
  frontend/src/page/LocationPage/views/AddLocationModalView.js
  frontend/src/page/LocationPage/views/DeleteLocationModalView.js
  frontend/src/page/LocationPage/views/ModelBlurBGView.js
  frontend/src/page/MenuPage/Controller.js
  frontend/src/page/MenuPage/Store.js
  frontend/src/page/MenuPage/index.js
  frontend/src/page/MenuPage/views/ModelBlurBGView.js
  frontend/src/page/MenuPage/views/SettingMenuModalView.js
  frontend/src/public/css/common/modal.css
Labels: BE, FE
